env:
  - GO111MODULE=on
before:
  hooks:
    - make setup
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*  
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: hupe1980
      name: homebrew-gotoaws
    homepage:  https://github.com/hupe1980/gotoaws
    description: gotoaws is an interactive CLI tool that you can use to connect to your AWS resources (EC2, ECS container) using the AWS Systems Manager Session Manager
    license: MIT
    test: |
      system "#{bin}/gotoaws -v"
    install: |-
      bin.install "gotoaws"
      bash_completion.install "completions/gotoaws.bash" => "gotoaws"
      zsh_completion.install "completions/gotoaws.zsh" => "_gotoaws"
      fish_completion.install "completions/gotoaws.fish"
scoop:
  bucket:
    owner: hupe1980
    name: gotoaws-bucket
  homepage:  https://github.com/hupe1980/gotoaws
  description: gotoaws is an interactive CLI tool that you can use to connect to your AWS resources (EC2, ECS container) using the AWS Systems Manager Session Manager
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/hupe1980/gotoaws
    maintainer: Frank Hübner <frankhuebner1980@gmail.com>
    description: gotoaws is an interactive CLI tool that you can use to connect to your AWS resources (EC2, ECS container) using the AWS Systems Manager Session Manager
    license: MIT
    contents:
      - src: ./completions/gotoaws.bash
        dst: /etc/bash_completion.d/gotoaws
      - src: ./completions/gotoaws.fish
        dst: /usr/share/fish/completions/gotoaws.fish
      - src: ./completions/gotoaws.zsh
        dst: /usr/local/share/zsh/site-functions/_gotoaws
    formats:
    - apk
    - deb
    - rpm
